In [1]:
import pandas as pd
#First look at the data
df = pd.read_csv("fraudTest.csv", index_col="trans_num")

df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

df.rename(columns= {df.columns[0]: "ID"} , inplace=True)

df

,ID,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,zip,lat,long,city_pop,job,dob,unix_time,merch_lat,merch_long,is_fraud
trans_num,,,,,,,,,,,,,,,,,,,,,
2da90c7d74bd46a0caf3777415b3ebd3,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,29209,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,1371816865,33.986391,-81.200714,0
324cc204407e99f51b0d6ca0055005e7,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,84002,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,1371816873,39.450498,-109.960431,0
c81755dbbbea9d5c77f094348a7579be,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,11710,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,1371816893,40.495810,-74.196111,0
2159175b9efe66dc301f149d3d5abf8c,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,32780,28.5697,-80.8191,54767,Set designer,1987-07-25,1371816915,28.812398,-80.883061,0
57ff021bd3f328f8738bb535c302a31b,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,49632,44.2529,-85.0170,1126,Furniture designer,1955-07-06,1371816917,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9b1f753c79894c9f4b71f04581835ada,555714,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,...,63453,40.4931,-91.8912,519,Town planner,1966-02-13,1388534347,39.946837,-91.333331,0
2090647dac2c89a1d86c514c427f5b91,555715,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,...,77566,29.0393,-95.4401,28739,Futures trader,1999-12-27,1388534349,29.661049,-96.186633,0
6c5b7c8add471975aa0fec023b2e8408,555716,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,...,99323,46.1966,-118.9017,3684,Musician,1981-11-29,1388534355,46.658340,-119.715054,0


In [2]:
print(df.info())

print(df.describe())

print(df.shape)

<class 'pandas.DataFrame'>
Index: 555719 entries, 2da90c7d74bd46a0caf3777415b3ebd3 to 1765bb45b3aa3224b4cdcb6e7a96cee3
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   ID                     555719 non-null  int64  
 1   trans_date_trans_time  555719 non-null  str    
 2   cc_num                 555719 non-null  int64  
 3   merchant               555719 non-null  str    
 4   category               555719 non-null  str    
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  str    
 7   last                   555719 non-null  str    
 8   gender                 555719 non-null  str    
 9   street                 555719 non-null  str    
 10  city                   555719 non-null  str    
 11  state                  555719 non-null  str    
 12  zip                    555719 non-null  int64  
 13  lat                    555719 non-null  float64


In [3]:
df['is_fraud'] = df['is_fraud'].astype(int)
print(df['is_fraud'].value_counts())

is_fraud
0    553574
1      2145
Name: count, dtype: int64


In [4]:
df['Merchant_Frequency'] = df['merchant'].map(df['merchant'].value_counts())

df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])

df['Hour'] = df['trans_date_trans_time'].dt.hour
df['Day_of_week'] = df['trans_date_trans_time'].dt.dayofweek
df['Is_weekend'] = df['Day_of_week'].isin([5,6]).astype(int)

df = df.drop('trans_date_trans_time', axis=1)

df['Transactions_per_user'] = df.groupby('cc_num')['amt'].transform('count')
df['Avg_amount_per_user'] = df.groupby('cc_num')['amt'].transform('mean')

df.head(3)

,ID,cc_num,merchant,category,amt,first,last,gender,street,city,...,unix_time,merch_lat,merch_long,is_fraud,Merchant_Frequency,Hour,Day_of_week,Is_weekend,Transactions_per_user,Avg_amount_per_user
trans_num,,,,,,,,,,,,,,,,,,,,,
2da90c7d74bd46a0caf3777415b3ebd3,0,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,...,1371816865,33.986391,-81.200714,0,736,12,6,1,640,61.893062
324cc204407e99f51b0d6ca0055005e7,1,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,...,1371816873,39.450498,-109.960431,0,785,12,6,1,837,53.596523
c81755dbbbea9d5c77f094348a7579be,2,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,Bellmore,...,1371816893,40.495810,-74.196111,0,755,12,6,1,1073,83.053812


In [5]:
X = df.select_dtypes(include=['number'])
X = X.drop(columns = ["ID", "is_fraud"])

y = df["is_fraud"]

print(X.shape)

(555719, 15)


In [6]:
# One Hot Encoding
from sklearn.preprocessing import OneHotEncoder
from scipy.sparse import hstack
import numpy as np

categorical_values = df.select_dtypes(include=['object', 'string'] )
encoder = OneHotEncoder(sparse_output = True, dtype= np.uint8, handle_unknown='ignore')
encoder.fit(categorical_values)
categorical_values_encoded = encoder.transform(categorical_values)

#Now, concatenating the encoded categorical values with the numerical features
categorical_values_encoded_df = pd.DataFrame.sparse.from_spmatrix(categorical_values_encoded, index = categorical_values.index,
                                                                  columns=encoder.get_feature_names_out(categorical_values.columns))
print(X.shape)


(555719, 15)


In [7]:
from sklearn.model_selection import train_test_split

# Splitting the testing and training data 80% - 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=10)


In [8]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=10)
X_train_scaled, y_train_scaled = smote.fit_resample(X_train, y_train)

In [9]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=50, n_jobs=-1,
                                    max_depth=None, min_samples_split=2, 
                                    criterion= 'gini', min_samples_leaf=1, 
                                    class_weight = 'balanced', random_state=10)

classifier.fit(X_train_scaled, y_train_scaled)


,n_estimators,50
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [ ]:
# I tried running the RandomizedSearchCV, but it took 99 mins to complete. So I just took the best hyperparams it gave me.
'''param_grid = {
    'n_estimators': [10, 20, 50, 100],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'criterion': ['gini', 'entropy'],
}

rand_search = RandomizedSearchCV(estimator=classifier, param_distributions=param_grid, cv=5, n_jobs=-1, scoring = 'f1', n_iter=30)

rand_search.fit(X_train_scaled, y_train_scaled)

print(f"Best parameters: {rand_search.best_params_}")
print(f"Best score: {rand_search.best_score_}")
'''

'''Best parameters: {'n_estimators': 50, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_depth': None, 'criterion': 'gini'}
Best score: 0.9990197300982956'''

In [11]:
y_predicted = classifier.predict(X_test)

y_probability = classifier.predict_proba(X_test)[:,1]

print(y_predicted, y_probability)
print(len(y_predicted), "                        ",len(y_probability))

[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
111144                          111144


In [12]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, precision_recall_curve, average_precision_score

print("Classification report: ")
print()
print(classification_report(y_test, y_predicted))
print()

print()
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_predicted))
print()

print()
print(f"ROC_AUC Score: {roc_auc_score(y_test, y_probability)}")
print()

print()
print("Precision-Recall Curve:")
precision, recall, thresholds = precision_recall_curve(y_test, y_probability)
for p, r, t in zip(precision, recall, thresholds):
    print(f"Threshold: {t:.2f}, Precision: {p:.2f}, Recall: {r:.2f}")

print()
print(f"Average Precision Score: {average_precision_score(y_test, y_probability)}")

Classification report: 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    110715
           1       0.65      0.77      0.70       429

    accuracy                           1.00    111144
   macro avg       0.82      0.88      0.85    111144
weighted avg       1.00      1.00      1.00    111144



Confusion Matrix:
[[110535    180]
 [    98    331]]


ROC_AUC Score: 0.9886071010986334


Precision-Recall Curve:
Threshold: 0.00, Precision: 0.00, Recall: 1.00
Threshold: 0.02, Precision: 0.03, Recall: 0.99
Threshold: 0.04, Precision: 0.05, Recall: 0.97
Threshold: 0.06, Precision: 0.08, Recall: 0.96
Threshold: 0.08, Precision: 0.10, Recall: 0.95
Threshold: 0.10, Precision: 0.12, Recall: 0.94
Threshold: 0.12, Precision: 0.15, Recall: 0.94
Threshold: 0.14, Precision: 0.17, Recall: 0.92
Threshold: 0.16, Precision: 0.19, Recall: 0.90
Threshold: 0.18, Precision: 0.21, Recall: 0.90
Threshold: 0.20, Precision: 0.24, Recall: 0.89
Threshold: 0.2

In [13]:
# Threshold tuning

from sklearn.metrics import precision_recall_curve
threshold = 0.3
y_predicted_custom = (y_probability > threshold).astype(int)

print(y_predicted_custom)

[0 0 0 ... 0 0 0]


In [ ]:
''' New features to add: 
1. Find a way to use the merchant name and category to create new features. Maybe use one hot encoding or something like that.
2. Use the day,hour and time of the transaction to create new features. Maybe use the hour of the day or the day of the week. 
Also track the number of operatins performed by each person. (Feature engineering.)
3. More hyperparameter tuning. Maybe use GridSearchCV or RandomizedSearchCV to find the best hyperparameters for the model.
4. Precision-recall curve and AUC-PR score. This is especially important for imbalanced datasets like this one.
5. Extra cross-validation using StratifiedKFOld and cross_val_score.
6. Extract insights from the model.
7. Threshold tuning. Find the best threshold for the model to maximize the F1 score or the precision-recall curve.
8. Most importantly, use matplotlib to visualize the data better.
9. Use feature importance to find the most important features for the model.
10. Test it with XGBoost and see.

11. Use SHAP values to explain the model predictions. (Not important right now so skippable.)
'''